### ISSUE TITLE
怎么没有17.2以上的真机包

### ISSUE THREAD

**Issue by GoldFishLi** [jijiucheng/JJC_iOS_DeviceSupport#6]
怎么没有17.2以上的真机包

**Comment by jijiucheng** [comment]
实际上从 Xcode15 和 iOS 17 开始，官方的 Xcode 就已经没有对应的真机包了，官方只有 iOS 16.4 的，所以建议尽早升级 Xcode 15 以上的版本吧---- 回复的原邮件 ***@***.***>发送日期2024年7月3日 ***@***.***>***@***.***>主题[jijiucheng/JJC_iOS_DeviceSupport] 怎么没有17.2以上的真机包 (Issue #6)怎么没有17.2以上的真机包—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
